version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: autenticacion
    ports:
      - "3307:3306"
  spring-app:
    container_name: spring_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.url=${SPRING_DATASOURCE_URL}
      - spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
      - spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


