version: '3'

services:
  # Servicio de RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # Servicio de MongoDB
  mongodb:
    image: mongo
    ports:
      - "27018:27017"

  # Servicio de aplicación en Go (Consumer-App)
  consumer-app:
    container_name: consumer-app
    build:
      context: .
      dockerfile: Dockerfile-Cons
    depends_on:
      - rabbitmq
      - mongodb

    # Servicio de aplicación en Go (REST-App)
  rest-app:
    container_name: rest-app
    build:
      context: .
      dockerfile: Dockerfile-REST
    depends_on:
      - mongodb
    ports:
      - "8091:8090"